# Site settings
title: Pranav Singh
email: pranavsingh.ps1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "If it's your best in this moment, that's the best it can be. Tomorrow your best may be completely different." -- Rick Rubin
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pranavsinghps1.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  pranavsinghps1

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Research Assistant"
excerpt_separator: "<!--more-->"

# SEO stuff
google_author: "https://scholar.google.com/citations?user=aUPq9a0AAAAJ&hl=en"
# google_site_verification: ""
# bing_webmastertools_id: ""
